name = "todo"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[vars]
RESEND_FROM = "service@codepapa.xyz"

[[d1_databases]]
binding = "DB"
database_name = "privatetodo-db"
database_id = "a4b77a06-ec57-41d4-8ec7-7dcf9c0ceb14"
